import {
  Smartphone,
  Shirt,
  Sofa,
  Sparkles,
  Dumbbell,
  BookOpen,
  Baby,
  Car,
  UtensilsCrossed,
  PawPrint,
  Gem,
  ToyBrick,
  ShoppingBag,
  ShoppingCart,
  Flower2,
  Wrench,
  Bike,
  Coffee,
  HeartPulse,
  type LucideIcon,
} from "lucide-react";

const ICON_BY_KEYWORD: Record<string, LucideIcon> = {
  electronic: Smartphone,
  tech: Smartphone,
  computer: Smartphone,
  phone: Smartphone,
  tablet: Smartphone,
  audio: Sparkles,
  fashion: Shirt,
  clothing: Shirt,
  apparel: Shirt,
  wear: Shirt,
  shoe: ShoppingBag,
  bag: ShoppingCart,
  accessor: Gem,
  home: Sofa,
  living: Sofa,
  furniture: Sofa,
  decor: Flower2,
  bedding: Sofa,
  beauty: Sparkles,
  cosmetic: Sparkles,
  skincare: HeartPulse,
  hair: Sparkles,
  health: HeartPulse,
  wellness: HeartPulse,
  sport: Dumbbell,
  fitness: Dumbbell,
  outdoor: Bike,
  book: BookOpen,
  media: BookOpen,
  baby: Baby,
  kid: Baby,
  child: Baby,
  toy: ToyBrick,
  automotive: Car,
  car: Car,
  auto: Car,
  food: UtensilsCrossed,
  grocery: UtensilsCrossed,
  grocer: UtensilsCrossed,
  kitchen: UtensilsCrossed,
  coffee: Coffee,
  drink: Coffee,
  pet: PawPrint,
  jewel: Gem,
  tool: Wrench,
};

export function getCategoryIcon(name: string): LucideIcon {
  const key = name.toLowerCase();
  for (const [keyword, icon] of Object.entries(ICON_BY_KEYWORD)) {
    if (key.includes(keyword)) return icon;
  }
  return ShoppingBag;
}
